# Generated by Django 4.1 on 2022-09-15 05:17

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
